{% set name = "stefuna" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc14e39260896a17d87302281c2e09197ead8273257c5d4ef01ed85fc55ca2b1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - stefuna = stefuna.stefuna:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3
    - boto3 >=1.4.6,<2.0.0

test:
  imports:
    - stefuna
  commands:
    - stefuna --help

about:
  home: https://github.com/irothschild/stefuna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Write an AWS Step Function Activity Server with a few lines of Python'

  description: |
    Stefuna is a simple AWS Step Function Activity server framework. It
    makes it incredibly quick and easy to write workers to process 
    activity tasks in Python.
  dev_url: https://github.com/irothschild/stefuna

extra:
  recipe-maintainers:
    - sodre
