travis:
  secure:
    BINSTAR_TOKEN: ofzw6PheXCxsu2JlUu5MJqF2V96gI0Rr0PqNffG67iGi4SxWzeL1z+mKKYFYiza3aqJxSK5DIXX3KvONPEcujtq5H3RiyzeOY1N6tDbDEWAIBevIJmiJSfY5k6zCg5punHOVLHfvDQjGoczLIWStkzK061i+NybhX9tRnBg9+JoF9DpYoAqB+yg9+juKpDfJL9eYguOdDScUt0dVoi8vbx43k2RMoEyFpopBRRvbxga+xrUrQsHm9e9YgWTCLK1sRolmB+u1JEnOPaYj4E0TdcwJv+B+pTqY3hFkyJpE4vrWidM2KoiJJ/+e55Lk/Qh5LUZvUzQbYKnBanmWtszYgUXTwd+D79f6ePtITadtTa81CG24ifl3I42BrGZjABIUkxiagYqHOoHI+Tuut9AJx4g9fORW902avqYBFFbfuoW863IH3KDpnztG8px97YzSaJCSeESZRGq5F9SHXqA9igqNy4W/Lw+2dY3Op23vTZVx1nhsQo5lWYVkXYAl1uYVmc/ylHHKS7bvkDjGPo7cAUoeZEPaaaEQvqiyXFZRumo77bYc3TxeBZ5ioI48RwmXm5FU0ijsqqO8iA6fUoTFDPgglPw7y1ulDFlZadWxXC6MAFwJdJLZ975H1obUIocSAJvn9LVLmIwzQiCND7MdIlDHL8U6W6qujVek3VE2qF0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
